"use client";

export type KeyType = {
  id: string;
  keyValue?: string;
  code?: string;
  label?: string;
  width?: number;
  icon?: string;
  gap?: number;
};

export type KeyboardLayout = {
  name: string;
  keys: KeyType[][];
};

export const qwertyLayout: KeyboardLayout = {
  name: "QWERTY",
  keys: [
    [
      { id: "key-escape", keyValue: "Escape", label: "Esc", code: "Escape" },
      { id: "spacing-1", gap: 1 },
      { id: "key-f1", keyValue: "F1", label: "F1", code: "F1" },
      { id: "key-f2", keyValue: "F2", label: "F2", code: "F2" },
      { id: "key-f3", keyValue: "F3", label: "F3", code: "F3" },
      { id: "key-f4", keyValue: "F4", label: "F4", code: "F4" },
      { id: "spacing-2", gap: 0.5 },
      { id: "key-f5", keyValue: "F5", label: "F5", code: "F5" },
      { id: "key-f6", keyValue: "F6", label: "F6", code: "F6" },
      { id: "key-f7", keyValue: "F7", label: "F7", code: "F7" },
      { id: "key-f8", keyValue: "F8", label: "F8", code: "F8" },
      { id: "spacing-3", gap: 0.5 },
      { id: "key-f9", keyValue: "F9", label: "F9", code: "F9" },
      { id: "key-f10", keyValue: "F10", label: "F10", code: "F10" },
      { id: "key-f11", keyValue: "F11", label: "F11", code: "F11" },
      { id: "key-f12", keyValue: "F12", label: "F12", code: "F12" },
      { id: "spacing-4", gap: 0.5 },
      {
        id: "key-printscreen",
        keyValue: "PrintScreen",
        label: "PrtSc",
        code: "PrintScreen",
      },
      {
        id: "key-scrolllock",
        keyValue: "ScrollLock",
        label: "ScrLk",
        code: "ScrollLock",
      },
      { id: "key-pause", keyValue: "Pause", label: "Pause", code: "Pause" },
    ],

    [
      { id: "key-backquote", keyValue: "`", label: "`", code: "Backquote" },
      { id: "key-1", keyValue: "1", label: "1", code: "Digit1" },
      { id: "key-2", keyValue: "2", label: "2", code: "Digit2" },
      { id: "key-3", keyValue: "3", label: "3", code: "Digit3" },
      { id: "key-4", keyValue: "4", label: "4", code: "Digit4" },
      { id: "key-5", keyValue: "5", label: "5", code: "Digit5" },
      { id: "key-6", keyValue: "6", label: "6", code: "Digit6" },
      { id: "key-7", keyValue: "7", label: "7", code: "Digit7" },
      { id: "key-8", keyValue: "8", label: "8", code: "Digit8" },
      { id: "key-9", keyValue: "9", label: "9", code: "Digit9" },
      { id: "key-0", keyValue: "0", label: "0", code: "Digit0" },
      { id: "key-minus", keyValue: "-", label: "-", code: "Minus" },
      { id: "key-equals", keyValue: "=", label: "=", code: "Equal" },
      {
        id: "key-backspace",
        keyValue: "Backspace",
        label: "Backspace",
        width: 1.9,
        code: "Backspace",
      },
      { id: "spacing-5", gap: 0.5 },
      { id: "key-insert", keyValue: "Insert", label: "Ins", code: "Insert" },
      { id: "key-home", keyValue: "Home", label: "Home", code: "Home" },
      { id: "key-pageup", keyValue: "PageUp", label: "PgUp", code: "PageUp" },
      { id: "spacing-6", gap: 0.5 },
      { id: "key-numlock", keyValue: "NumLock", label: "Num", code: "NumLock" },
      {
        id: "key-numpad-divide",
        keyValue: "/",
        label: "/",
        code: "NumpadDivide",
      },
      {
        id: "key-numpad-multiply",
        keyValue: "*",
        label: "*",
        code: "NumpadMultiply",
      },
      {
        id: "key-numpad-subtract",
        keyValue: "-",
        label: "-",
        code: "NumpadSubtract",
      },
    ],

    [
      { id: "key-tab", keyValue: "Tab", label: "Tab", width: 1.5, code: "Tab" },
      { id: "key-q", keyValue: "q", label: "Q", code: "KeyQ" },
      { id: "key-w", keyValue: "w", label: "W", code: "KeyW" },
      { id: "key-e", keyValue: "e", label: "E", code: "KeyE" },
      { id: "key-r", keyValue: "r", label: "R", code: "KeyR" },
      { id: "key-t", keyValue: "t", label: "T", code: "KeyT" },
      { id: "key-y", keyValue: "y", label: "Y", code: "KeyY" },
      { id: "key-u", keyValue: "u", label: "U", code: "KeyU" },
      { id: "key-i", keyValue: "i", label: "I", code: "KeyI" },
      { id: "key-o", keyValue: "o", label: "O", code: "KeyO" },
      { id: "key-p", keyValue: "p", label: "P", code: "KeyP" },
      { id: "key-openbracket", keyValue: "[", label: "[", code: "BracketLeft" },
      {
        id: "key-closebracket",
        keyValue: "]",
        label: "]",
        code: "BracketRight",
      },
      {
        id: "key-backslash",
        keyValue: "\\",
        label: "\\",
        width: 1.4,
        code: "Backslash",
      },
      { id: "spacing-7", gap: 0.5 },
      { id: "key-delete", keyValue: "Delete", label: "Del", code: "Delete" },
      { id: "key-end", keyValue: "End", label: "End", code: "End" },
      {
        id: "key-pagedown",
        keyValue: "PageDown",
        label: "PgDn",
        code: "PageDown",
      },
      { id: "spacing-8", gap: 0.5 },
      { id: "key-numpad-7", keyValue: "Numpad7", label: "7", code: "Numpad7" },
      { id: "key-numpad-8", keyValue: "Numpad8", label: "8", code: "Numpad8" },
      { id: "key-numpad-9", keyValue: "Numpad9", label: "9", code: "Numpad9" },
      {
        id: "key-numpad-add",
        keyValue: "NumpadAdd",
        label: "+",
        width: 1,
        code: "NumpadAdd",
      },
    ],

    [
      {
        id: "key-capslock",
        keyValue: "CapsLock",
        label: "Caps Lock",
        width: 1.75,
        code: "CapsLock",
      },
      { id: "key-a", keyValue: "a", label: "A", code: "KeyA" },
      { id: "key-s", keyValue: "s", label: "S", code: "KeyS" },
      { id: "key-d", keyValue: "d", label: "D", code: "KeyD" },
      { id: "key-f", keyValue: "f", label: "F", code: "KeyF" },
      { id: "key-g", keyValue: "g", label: "G", code: "KeyG" },
      { id: "key-h", keyValue: "h", label: "H", code: "KeyH" },
      { id: "key-j", keyValue: "j", label: "J", code: "KeyJ" },
      { id: "key-k", keyValue: "k", label: "K", code: "KeyK" },
      { id: "key-l", keyValue: "l", label: "L", code: "KeyL" },
      { id: "key-semicolon", keyValue: ";", label: ";", code: "Semicolon" },
      { id: "key-quote", keyValue: "'", label: "'", code: "Quote" },
      {
        id: "key-enter",
        keyValue: "Enter",
        label: "Enter",
        width: 2.25,
        code: "Enter",
      },
      { id: "spacing-9", gap: 4.3 },
      { id: "key-numpad-4", keyValue: "Numpad4", label: "4", code: "Numpad4" },
      { id: "key-numpad-5", keyValue: "Numpad5", label: "5", code: "Numpad5" },
      { id: "key-numpad-6", keyValue: "Numpad6", label: "6", code: "Numpad6" },
      {
        id: "key-numpad-comma",
        keyValue: "NumpadComma",
        label: ".",
        code: "NumpadDecimal",
      },
    ],

    [
      {
        id: "key-shiftleft",
        keyValue: "ShiftLeft",
        label: "Shift",
        width: 2.35,
        code: "ShiftLeft",
      },
      { id: "key-z", keyValue: "z", label: "Z", code: "KeyZ" },
      { id: "key-x", keyValue: "x", label: "X", code: "KeyX" },
      { id: "key-c", keyValue: "c", label: "C", code: "KeyC" },
      { id: "key-v", keyValue: "v", label: "V", code: "KeyV" },
      { id: "key-b", keyValue: "b", label: "B", code: "KeyB" },
      { id: "key-n", keyValue: "n", label: "N", code: "KeyN" },
      { id: "key-m", keyValue: "m", label: "M", code: "KeyM" },
      { id: "key-comma", keyValue: ",", label: ",", code: "Comma" },
      { id: "key-period", keyValue: ".", label: ".", code: "Period" },
      { id: "key-slash", keyValue: "/", label: "/", code: "Slash" },
      {
        id: "key-shiftright",
        keyValue: "ShiftRight",
        label: "Shift",
        width: 2.75,
        code: "ShiftRight",
      },
      { id: "spacing-10", gap: 1.6 },
      { id: "key-arrowup", keyValue: "ArrowUp", label: "↑", code: "ArrowUp" },
      { id: "spacing-11", gap: 1.6 },
      { id: "key-numpad-1", keyValue: "Numpad1", label: "1", code: "Numpad1" },
      { id: "key-numpad-2", keyValue: "Numpad2", label: "2", code: "Numpad2" },
      { id: "key-numpad-3", keyValue: "Numpad3", label: "3", code: "Numpad3" },
      {
        id: "key-numpad-enter",
        keyValue: "NumpadEnter",
        label: "Enter",
        width: 1,
        code: "NumpadEnter",
      },
    ],

    [
      {
        id: "key-controlleft",
        keyValue: "ControlLeft",
        label: "Ctrl",
        width: 1.25,
        code: "ControlLeft",
      },
      {
        id: "key-metaleft",
        keyValue: "Meta",
        label: "Win",
        width: 1.25,
        code: "MetaLeft",
      },
      {
        id: "key-altleft",
        keyValue: "AltLeft",
        label: "Alt",
        width: 1.25,
        code: "AltLeft",
      },
      {
        id: "key-space",
        keyValue: " ",
        label: "Space",
        width: 6.25,
        code: "Space",
      },
      {
        id: "key-altright",
        keyValue: "AltRight",
        label: "Alt Gr",
        width: 1.5,
        code: "AltRight",
      },
      {
        id: "key-metaright",
        keyValue: "Meta",
        label: "Win",
        width: 1.25,
        code: "MetaRight",
      },
      { id: "key-fn", keyValue: "Fn", label: "Fn", width: 1.25, code: "Fn" },
      {
        id: "key-controlright",
        keyValue: "ControlRight",
        label: "Ctrl",
        width: 1.5,
        code: "ControlRight",
      },
      { id: "spacing-12", gap: 0.5 },
      {
        id: "key-arrowleft",
        keyValue: "ArrowLeft",
        label: "←",
        code: "ArrowLeft",
      },
      {
        id: "key-arrowdown",
        keyValue: "ArrowDown",
        label: "↓",
        code: "ArrowDown",
      },
      {
        id: "key-arrowright",
        keyValue: "ArrowRight",
        label: "→",
        code: "ArrowRight",
      },
      { id: "spacing-14", gap: 0.5 },
      {
        id: "key-numpad-0",
        keyValue: "Numpad0",
        label: "0",
        width: 2.1,
        code: "Numpad0",
      },
      {
        id: "key-numpad-decimal",
        keyValue: "NumpadDecimal",
        label: ",",
        code: "NumpadDecimal",
      },
    ],
  ],
};

export const layouts: KeyboardLayout[] = [qwertyLayout];
