export type KeyType = {
  id: string;
  keyValue?: string;
  label?: string;
  width?: number;
  icon?: string;
  gap?: number;
};

export type KeyboardLayout = {
  name: string;
  keys: KeyType[][];
};

export const qwertyLayout: KeyboardLayout = {
  name: "QWERTY",
  keys: [
    [
      { id: "key-escape", keyValue: "Escape", label: "Esc" },
      { id: "spacing-1", gap: 1 },
      { id: "key-f1", keyValue: "F1", label: "F1" },
      { id: "key-f2", keyValue: "F2", label: "F2" },
      { id: "key-f3", keyValue: "F3", label: "F3" },
      { id: "key-f4", keyValue: "F4", label: "F4" },
      { id: "spacing-2", gap: 0.5 },
      { id: "key-f5", keyValue: "F5", label: "F5" },
      { id: "key-f6", keyValue: "F6", label: "F6" },
      { id: "key-f7", keyValue: "F7", label: "F7" },
      { id: "key-f8", keyValue: "F8", label: "F8" },
      { id: "spacing-3", gap: 0.5 },
      { id: "key-f9", keyValue: "F9", label: "F9" },
      { id: "key-f10", keyValue: "F10", label: "F10" },
      { id: "key-f11", keyValue: "F11", label: "F11" },
      { id: "key-f12", keyValue: "F12", label: "F12" },
      { id: "spacing-4", gap: 0.5 },
      { id: "key-printscreen", keyValue: "PrintScreen", label: "PrtSc" },
      { id: "key-scrolllock", keyValue: "ScrollLock", label: "ScrLk" },
      { id: "key-pause", keyValue: "Pause", label: "Pause" },
    ],
    [
      { id: "key-backquote", keyValue: "`", label: "`" },
      { id: "key-1", keyValue: "1", label: "1" },
      { id: "key-2", keyValue: "2", label: "2" },
      { id: "key-3", keyValue: "3", label: "3" },
      { id: "key-4", keyValue: "4", label: "4" },
      { id: "key-5", keyValue: "5", label: "5" },
      { id: "key-6", keyValue: "6", label: "6" },
      { id: "key-7", keyValue: "7", label: "7" },
      { id: "key-8", keyValue: "8", label: "8" },
      { id: "key-9", keyValue: "9", label: "9" },
      { id: "key-0", keyValue: "0", label: "0" },
      { id: "key-minus", keyValue: "-", label: "-" },
      { id: "key-equals", keyValue: "=", label: "=" },
      {
        id: "key-backspace",
        keyValue: "Backspace",
        label: "Backspace",
        width: 1.9,
      },
      { id: "spacing-5", gap: 0.5 },
      { id: "key-insert", keyValue: "Insert", label: "Ins" },
      { id: "key-home", keyValue: "Home", label: "Home" },
      { id: "key-pageup", keyValue: "PageUp", label: "PgUp" },
      { id: "spacing-6", gap: 0.5 },
      { id: "key-numlock", keyValue: "NumLock", label: "Num" },
      { id: "key-numpad-divide", keyValue: "NumpadDivide", label: "/" },
      { id: "key-numpad-multiply", keyValue: "NumpadMultiply", label: "*" },
      { id: "key-numpad-subtract", keyValue: "NumpadSubtract", label: "-" },
    ],
    [
      { id: "key-tab", keyValue: "Tab", label: "Tab", width: 1.5 },
      { id: "key-q", keyValue: "q", label: "Q" },
      { id: "key-w", keyValue: "w", label: "W" },
      { id: "key-e", keyValue: "e", label: "E" },
      { id: "key-r", keyValue: "r", label: "R" },
      { id: "key-t", keyValue: "t", label: "T" },
      { id: "key-y", keyValue: "y", label: "Y" },
      { id: "key-u", keyValue: "u", label: "U" },
      { id: "key-i", keyValue: "i", label: "I" },
      { id: "key-o", keyValue: "o", label: "O" },
      { id: "key-p", keyValue: "p", label: "P" },
      { id: "key-openbracket", keyValue: "[", label: "[" },
      { id: "key-closebracket", keyValue: "]", label: "]" },
      { id: "key-backslash", keyValue: "\\", label: "\\", width: 1.4 },
      { id: "spacing-7", gap: 0.5 },
      { id: "key-delete", keyValue: "Delete", label: "Del" },
      { id: "key-end", keyValue: "End", label: "End" },
      { id: "key-pagedown", keyValue: "PageDown", label: "PgDn" },
      { id: "spacing-8", gap: 0.5 },
      { id: "key-numpad-7", keyValue: "Numpad7", label: "7" },
      { id: "key-numpad-8", keyValue: "Numpad8", label: "8" },
      { id: "key-numpad-9", keyValue: "Numpad9", label: "9" },
      { id: "key-numpad-add", keyValue: "NumpadAdd", label: "+", width: 1 },
    ],
    [
      {
        id: "key-capslock",
        keyValue: "CapsLock",
        label: "Caps Lock",
        width: 1.75,
      },
      { id: "key-a", keyValue: "a", label: "A" },
      { id: "key-s", keyValue: "s", label: "S" },
      { id: "key-d", keyValue: "d", label: "D" },
      { id: "key-f", keyValue: "f", label: "F" },
      { id: "key-g", keyValue: "g", label: "G" },
      { id: "key-h", keyValue: "h", label: "H" },
      { id: "key-j", keyValue: "j", label: "J" },
      { id: "key-k", keyValue: "k", label: "K" },
      { id: "key-l", keyValue: "l", label: "L" },
      { id: "key-semicolon", keyValue: ";", label: ";" },
      { id: "key-quote", keyValue: "'", label: "'" },
      { id: "key-enter", keyValue: "Enter", label: "Enter", width: 2.25 },
      { id: "spacing-9", gap: 4.3 },
      { id: "key-numpad-4", keyValue: "Numpad4", label: "4" },
      { id: "key-numpad-5", keyValue: "Numpad5", label: "5" },
      { id: "key-numpad-6", keyValue: "Numpad6", label: "6" },
      { id: "key-numpad-comma", keyValue: "NumpadComma", label: "." },
    ],
    [
      {
        id: "key-shiftleft",
        keyValue: "ShiftLeft",
        label: "Shift",
        width: 2.35,
      },
      { id: "key-z", keyValue: "z", label: "Z" },
      { id: "key-x", keyValue: "x", label: "X" },
      { id: "key-c", keyValue: "c", label: "C" },
      { id: "key-v", keyValue: "v", label: "V" },
      { id: "key-b", keyValue: "b", label: "B" },
      { id: "key-n", keyValue: "n", label: "N" },
      { id: "key-m", keyValue: "m", label: "M" },
      { id: "key-comma", keyValue: ",", label: "," },
      { id: "key-period", keyValue: ".", label: "." },
      { id: "key-slash", keyValue: "/", label: "/" },
      {
        id: "key-shiftright",
        keyValue: "ShiftRight",
        label: "Shift",
        width: 2.75,
      },
      { id: "spacing-10", gap: 1.6 },
      { id: "key-arrowup", keyValue: "ArrowUp", label: "↑" },
      { id: "spacing-11", gap: 1.6 },
      { id: "key-numpad-1", keyValue: "Numpad1", label: "1" },
      { id: "key-numpad-2", keyValue: "Numpad2", label: "2" },
      { id: "key-numpad-3", keyValue: "Numpad3", label: "3" },
      {
        id: "key-numpad-enter",
        keyValue: "NumpadEnter",
        label: "Enter",
        width: 1,
      },
    ],
    [
      {
        id: "key-controlleft",
        keyValue: "ControlLeft",
        label: "Ctrl",
        width: 1.25,
      },
      { id: "key-metaleft", keyValue: "Meta", label: "Win", width: 1.25 },
      { id: "key-altleft", keyValue: "AltLeft", label: "Alt", width: 1.25 },
      { id: "key-space", keyValue: " ", label: "Space", width: 6.25 },
      { id: "key-altright", keyValue: "AltRight", label: "Alt Gr", width: 1.5 },
      { id: "key-metaright", keyValue: "Meta", label: "Win", width: 1.25 },
      { id: "key-fn", keyValue: "Fn", label: "Fn", width: 1.25 },
      {
        id: "key-controlright",
        keyValue: "ControlRight",
        label: "Ctrl",
        width: 1.5,
      },
      { id: "spacing-12", gap: 0.5 },
      { id: "key-arrowleft", keyValue: "ArrowLeft", label: "←" },
      { id: "key-arrowdown", keyValue: "ArrowDown", label: "↓" },
      { id: "key-arrowright", keyValue: "ArrowRight", label: "→" },
      { id: "spacing-14", gap: 0.5 },
      { id: "key-numpad-0", keyValue: "Numpad0", label: "0", width: 2.1 },
      { id: "key-numpad-decimal", keyValue: "NumpadDecimal", label: "," },
    ],
  ],
};

export const layouts: KeyboardLayout[] = [qwertyLayout];
